### ISSUE TITLE
[Question]: does it work with VIte?

### ISSUE THREAD

**Issue by Vendjin** [codegowhere/react-inject-env#26]

**Comment by william-incode** [comment]
I did it work with vite just changed the export for this one:

export const env: EnvType = { ...import.meta.env, ...window.env }

and in the import of html file:
<script type="module" src='./src/env.ts'></script>

**Comment by william-incode** [comment]
forget that i found a fork for vite env and is working correctly https://www.npmjs.com/package/vite-inject-env

**Comment by Vendjin** [comment]
yes, I also found it later and used it, thanks for your answer
