### ISSUE TITLE
[Question] How do you handle PUBLIC_URL

### ISSUE THREAD

**Issue by kirilpopov** [codegowhere/react-inject-env#7]
Thank you for the effort of creating this, it is really usefull.

I have a question which is related to the purpose of the lib - in the typical Create React App you would have some usage of **PUBLIC_URL** in the index.html file , e.g.

```html
<!--
    manifest.json provides metadata used when your web app is installed on a
    user's mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
-->
link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
```

Typically this is resolved from env vars (either .env file or setting them directly) on build time.

Can you share some advice about how you handle this, so it's changeable after build time (e.g. can be replaced in a Docker image which is already built)?

**Comment by aelesia** [comment]
PUBLIC_URL is now supported in `v2.1.0` using the [build / inject workflow](https://github.com/codegowhere/react-inject-env/blob/master/docs/v1.md)

Note: This is not supported by the `set` workflow as I'm not aware of any way to for `index.html` to read from `window` (except for maybe using `document.setElementById`).
